package net.karlmartens.euler.p0002;

public final class Solution01 {

	/**
	 * <p>
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first terms will be:
	 * </p>
	 * 
	 * <p style="text-indent: 50px">
	 * 0, 1, 1, 2, 3, 5, 8, 13, 31, 34, 55, 89, ..
	 * </p>
	 * 
	 * <p>
	 * By considering the terms in the Fibonacci sequence whose values do not
	 * exceed four million, find the sum of the even-valued terms.
	 * </p>
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		int total = 0;
		int a = 0;
		int b = 1;
		int c = 1;
		for (;;) {
			if (a > 4000000)
				break;

			total += a;
			a = b + c;
			b = c + a;
			c = a + b;
		}

		System.out.println(total);
	}

}
